arch:
  - amd64
  - ppc64le
language: java
jdk:
  - openjdk11
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V > narayana.log
  - tail -300 narayana.log
Tests:
  - mvn test -B
